[package]
name = "lcmg"
version = "0.1.0"
authors = ["aegroto <aegroto@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mp4 = "0.8.1"
h264-reader = "0.4.0"
